fish:
  BeginFishLocation:
    - 925
    - 825

  # 1220, 224
  FishLocation:
    - 908
    - 173
  # 211 218 215
  FishColor:
    red:   231
    green: 218
    blue:  216

  # 1159, 463
  StruggleLocation:
    - 1048
    - 357

  #  110, 64, 85
  StruggleColor:
    red: 110
    green: 64
    blue: 85